ex1AspNetCore/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ex1AspNetCore.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ex1AspNetCore/Pages/Index.cshtml.cs
using CsvHelper;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Caching.Memory;
using System.Linq;

namespace ex1AspNetCore.Pages
{
    public class IndexModel : PageModel
    {
        private const string FilePath = "books.csv";

        [BindProperty]
        public Book Book { get; set; }

        [BindProperty]
        public string searchTerm { get; set; }

        [BindProperty]
        public string BookTitle { get; set; }

        [BindProperty]
        public string BookAuthor { get; set; }

        public Dictionary<int, Book> Books = new Dictionary<int, Book>();
        public List<Book> SearchResults { get; set; } 
        public bool SearchError { get; set; }

        private readonly string _cacheKey = "BooksCache";

        private readonly IMemoryCache _cache;
        public IndexModel(IMemoryCache cache)
        {
            _cache = cache;
        }
        public void OnGet()
        {
            Books = ReadBooksFromFile();
            _cache.Set<Dictionary<int, Book>>(_cacheKey, Books); //storing the books in the cache
        }

        private Dictionary<int, Book> ReadBooksFromFile()
        {
            var books = new Dictionary<int, Book>();
            using (var reader = new StreamReader(FilePath))
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                csv.Read();
                csv.ReadHeader();

                while (csv.Read())
                {
                    if (csv.TryGetField<int>("bookID", out int id)
                        && csv.TryGetField("title", out string title)
                        && csv.TryGetField("authors", out string authors))
                        //returns true if the parsing is successful
                    {
                        Book book = new Book
                        {
                            bookID = id,
                            title = title,
                            authors = authors,
                        };

                        books.Add(id, book);
                    }
                }
            }
            return books;
        }

        public void OnPostAdd()
        {
            try
            {
                AddBook();
                ViewData["MessageAdd"] = "New book added successfuly";
                // allows to pass data from the controller to the view
            }
            catch (Exception ex)
            {
                ViewData["MessageAdd"] = $"Adding new book was failed due to {ex}";
            }
        }

        private void AddBook()
        {
            Books = _cache.Get<Dictionary<int, Book>>(_cacheKey);
            int last_index = Books.Keys.Last(); //saves the last key added 
            Book newBook = new Book
            {
                bookID = last_index + 1, //so each new book will get the next key value (I found it redundant to let the user insert id) 
                title = BookTitle,
                authors = BookAuthor
            };
            Books.Add(newBook.bookID, newBook);
            _cache.Set(_cacheKey, Books);

            using (StreamWriter writer = new StreamWriter(FilePath, true))
            {
                string newRow = $"{newBook.bookID}, {newBook.title}, {newBook.authors}";
                writer.WriteLine(newRow);
            }
        }

        public void OnPostSearch()
        {
            SearchResults = SearchBook();    
        }

        private List<Book> SearchBook()
        {
            Dictionary<int, Book> books = _cache.Get<Dictionary<int, Book>>(_cacheKey);
            List<Book> results = new List<Book>();

            if (string.IsNullOrEmpty(searchTerm) || !IsValidSearchTerm(searchTerm))
            {
                SearchError = true;
                return results;
            }

            foreach (Book book in books.Values)
            {
                if (book.title.IndexOf(searchTerm, StringComparison.OrdinalIgnoreCase) >= 0 ||
                    book.bookID.ToString().Equals(searchTerm, StringComparison.OrdinalIgnoreCase))
                //specifies case-insensitive comparison
                {
                    results.Add(book);
                }
            }

            return results;
        }

        private bool IsValidSearchTerm(string searchTerm)
        {
            // the first condition checks if the searchTerm is a single digit

            return Regex.IsMatch(searchTerm, @"^\d$") || Regex.IsMatch(searchTerm, @"^[a-zA-Z0-9\s]*$");

            //the second consition checks if the searchTerm contains only letters, digits, and spaces
        }

        public void OnPostDelete()
        {
            bool status = DeleteBook();
            if (status)
            {
                ViewData["MessageDelete"] = "Book deleted successfuly";
            }
            else
            {
                ViewData["MessageDelete"] = "There is no such book available. Please try again.";
            }
        }

        private bool DeleteBook()
        {
            Books = _cache.Get<Dictionary<int, Book>>(_cacheKey);
            if (int.TryParse(BookId, out int bookIdValue) && Books.Remove(bookIdValue))
            //The Remove method returns a boolean indicating whether the removal was successful
            {
                using (StreamWriter writer = new StreamWriter(FilePath, false))
                {
                    using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
                    {
                        csv.WriteRecords(Books.Values);
                    }
                }
                _cache.Set(_cacheKey, Books);
                return true;
            }
            return false;
        }
    }
}

ex1AspNetCore/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ex1AspNetCore.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ex1AspNetCore/Pages/Index.cshtml
@page
@model ex1AspNetCore.Pages.IndexModel

<h2>Book Search</h2>

<form asp-page-handler="Search" method="post">
    <div>
        <label asp-for="searchTerm">searchTerm:</label>
        <input required asp-for="searchTerm"/>
        <button type="submit">Search</button>
    </div>
</form>
<!-- I will render the results in this cases: 
     - if the user inserted the exact id for the book
     - if the user inserted part of the title or the whole title
-->
@if (Model.SearchResults != null)
{
    @if (Model.SearchError)
    {
        <p>Invalid search term. Only letters and digits are allowed. Please provide at least 2 letters.</p>       
    }
    else if (Model.SearchResults.Count() == 0)
    {
        <p>No matching books found.</p>
    }
    else
    {
        <h4>Search Results:</h4>
        <p>Results found: @Model.SearchResults.Count</p>
        <table>
            <thead>
                <tr>
                    <th>Book ID</th>
                    <th>Title</th>
                    <th>Authors</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Book book in Model.SearchResults)
                {
                    <tr>
                        <td>@book.bookID</td>
                        <td>@book.title</td>
                        <td>@book.authors</td>
                    </tr>
                }
            </tbody>
        </table>
    }
}
<br />
<br />
<h2>Add New Book</h2>

<form asp-page-handler="Add" method="post">  
    <div>
        <label asp-for="BookTitle">BookTitle:</label>
        <input asp-for="BookTitle" required />
        <label asp-for="BookAuthor">BookAuthors:</label>
        <input asp-for="BookAuthor" required />
        <button type="submit">Add Book</button>
    </div>
</form>
@if (ViewData["MessageAdd"] != null)
{
    <p>@ViewData["MessageAdd"]</p>
}
<br />
<br />
<h2>Delete Book by id</h2>
<form asp-page-handler="Delete" method="post">  
    <div>
        <label asp-for="BookId">BookID:</label>
        <input required asp-for="BookId"/>
        <button type="submit">Delete</button>
    </div>
</form>
@if (ViewData["MessageDelete"] != null)
{
    <p>@ViewData["MessageDelete"]</p>
}

ex1AspNetCore/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ex1AspNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ex1AspNetCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ex1AspNetCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ex1AspNetCore - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>